---
name:                "ci"

on:
  # schedule:
  #   - cron:        "0 21 * * *"
  push:

env:
  DOCKER_USER:       "pandemonium1986"
  DOCKER_IMAGE:      "alpine312"
  DOCKER_TAG:        "latest"

jobs:
  docker:
    name:            "Docker: Build and Push"
    runs-on:         ubuntu-latest
    steps:
      - name:        Checkout
        uses:        actions/checkout@v2
      - name:        Login to GitHub Container Registry
        uses:        docker/login-action@v1
        with:
          registry:  ghcr.io
          username:  ${{ github.repository_owner }}
          password:  ${{ secrets.CR_PAT }}
      - name:        Set up Docker Buildx
        id:          buildx
        uses:        docker/setup-buildx-action@v1
        with:
          version:   latest
      - name:        Build and push
        id:          docker_build
        uses:        docker/build-push-action@v2
        with:
          context:   .
          file:      ./Dockerfile
          platforms: linux/amd64
          push:      false
          tags:      |
            ghcr.io/${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
      - name:        Image digest
        run:         echo ${{ steps.docker_build.outputs.digest }}
