---
name:                          "docker"

on:
  # schedule:
  #   - cron:                  "0 21 * * *"
  push:

env:
  DOCKER_TAG:                  "latest"

jobs:
  lint:
    name:                      "GitHub => Super Linter"
    runs-on:                   ubuntu-latest
    steps:
    - name:                    "Init => Run checkout@v2"
      uses:                    actions/checkout@v2
      with:
        fetch-depth:           0
    - name:                    "GitHub => Lint Dockerfile"
      uses:                    github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH:        master
        GITHUB_TOKEN:          ${{ secrets.GITHUB_TOKEN }}
  docker:
    name:                      "Docker => Build and Push"
    runs-on:                   ubuntu-latest
    needs:
      - lint
    steps:
      - name:                  "Init => Checkout"
        uses:                  actions/checkout@v2
      - name:                  "Prepare => Get the version from the tag"
        run:                   echo RELEASE_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_ENV
      - name:                  "Docker => Login to GitHub Container Registry"
        uses:                  docker/login-action@v1
        with:
          registry:            ghcr.io
          username:            ${{ github.repository_owner }}
          password:            ${{ secrets.CR_PAT }}
      - name:                  "Docker => Set up Docker Buildx"
        id:                    buildx
        uses:                  docker/setup-buildx-action@v1
        with:
          version:             latest
      - name:                  "Docker => Build and push"
        id:                    docker_build
        uses:                  docker/build-push-action@v2
        with:
          context:             .
          file:                ./Dockerfile
          platforms:           linux/amd64
          push:                true
          tags:                |
            ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }}
      - name:                  "Docker => Image digest"
        run:                   echo ${{ steps.docker_build.outputs.digest }}
